### ISSUE TITLE
QA about setup

### ISSUE THREAD

**Issue by gerroon** [aawsome/mopidy-snapcast#4]
[snapcast]
    enabled = true
    host = snapserver.local
    port = 1234

I am  confused about this. Is this supposed to be the host and port of the runnin g snapcast or this plugin runs itself as something elss, because the default port for snapcast is 1705 not 1234. 

Also you give another example right below, are they separate examples or I have to set all together?

thanks

**Comment by aawsome** [comment]
Ups - sorry, forgot to answer to this question...

- yes it is supposed to be the host and port of the running snapcast, i.e. port 1705 should work with the default port.
- they are two independent examples. I bet the second example is what you maybe want to try iout...
